<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\LiteNova.LitePress.Application.Write.Contracts\LiteNova.LitePress.Application.Write.Contracts.csproj" />
    <ProjectReference Include="..\LiteNova.LitePress.Application.Read.Contracts\LiteNova.LitePress.Application.Read.Contracts.csproj" />
    <ProjectReference Include="..\LiteNova.LitePress.Infrastructure\LiteNova.LitePress.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="LiteBus.Commands.Abstractions" />
    <PackageReference Include="LiteBus.Queries.Abstractions" />
    <PackageReference Include="LiteBus.Extensions.Microsoft.DependencyInjection" />
    <PackageReference Include="LiteBus.Commands.Extensions.Microsoft.DependencyInjection" />
    <PackageReference Include="LiteBus.Queries.Extensions.Microsoft.DependencyInjection" />
    <PackageReference Include="LiteBus.Events.Extensions.Microsoft.DependencyInjection" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
