// <auto-generated />
using System;
using LiteNova.Blog.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LiteNova.Blog.Infrastructure.Migrations;
[DbContext(typeof(BlogDbContext))]
[Migration("20260521154201_InitialCreate")]
partial class InitialCreate
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.4")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("LiteNova.Blog.Domain.Authors.Author", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<string>("DisplayName")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)")
                    .HasColumnName("display_name");

                b.Property<string>("ExternalId")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)")
                    .HasColumnName("external_id");

                b.Property<DateTimeOffset>("RegisteredAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("registered_at");

                b.HasKey("Id");

                b.HasIndex("ExternalId")
                    .IsUnique()
                    .HasDatabaseName("uq_authors_external_id");

                b.ToTable("authors", (string)null);
            });

        modelBuilder.Entity("LiteNova.Blog.Domain.Posts.Post", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<DateTimeOffset?>("ArchivedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("archived_at");

                b.Property<Guid>("AuthorId")
                    .HasColumnType("uuid")
                    .HasColumnName("author_id");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at");

                b.Property<DateTimeOffset?>("PublishedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("published_at");

                b.Property<DateTimeOffset>("UpdatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("updated_at");

                b.Property<string>("_stateType")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("character varying(20)")
                    .HasColumnName("state");

                b.HasKey("Id");

                b.HasIndex("AuthorId")
                    .HasDatabaseName("ix_posts_author_id");

                b.ToTable("posts", (string)null);
            });

        modelBuilder.Entity("LiteNova.Blog.Domain.Posts.PostTag", b =>
            {
                b.Property<Guid>("PostId")
                    .HasColumnType("uuid")
                    .HasColumnName("post_id");

                b.Property<Guid>("TagId")
                    .HasColumnType("uuid")
                    .HasColumnName("tag_id");

                b.HasKey("PostId", "TagId");

                b.HasIndex("TagId")
                    .HasDatabaseName("ix_post_tags_tag_id");

                b.ToTable("post_tags", (string)null);
            });

        modelBuilder.Entity("LiteNova.Blog.Domain.Tags.Tag", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uuid")
                    .HasColumnName("id");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at");

                b.HasKey("Id");

                b.ToTable("tags", (string)null);
            });

        modelBuilder.Entity("LiteNova.Blog.Domain.Posts.Post", b =>
            {
                b.OwnsOne("LiteNova.Blog.Domain.Posts.PostContent", "Content", b1 =>
                    {
                        b1.Property<Guid>("PostId")
                            .HasColumnType("uuid");

                        b1.Property<string>("Value")
                            .IsRequired()
                            .HasColumnType("text")
                            .HasColumnName("content");

                        b1.HasKey("PostId");

                        b1.ToTable("posts");

                        b1.WithOwner()
                            .HasForeignKey("PostId");
                    });

                b.OwnsOne("LiteNova.Blog.Domain.Posts.PostCoverImageUrl", "CoverImageUrl", b1 =>
                    {
                        b1.Property<Guid>("PostId")
                            .HasColumnType("uuid");

                        b1.Property<string>("Value")
                            .IsRequired()
                            .HasMaxLength(2048)
                            .HasColumnType("character varying(2048)")
                            .HasColumnName("cover_image_url");

                        b1.HasKey("PostId");

                        b1.ToTable("posts");

                        b1.WithOwner()
                            .HasForeignKey("PostId");
                    });

                b.OwnsOne("LiteNova.Blog.Domain.Posts.PostExcerpt", "Excerpt", b1 =>
                    {
                        b1.Property<Guid>("PostId")
                            .HasColumnType("uuid");

                        b1.Property<string>("Value")
                            .IsRequired()
                            .HasMaxLength(500)
                            .HasColumnType("character varying(500)")
                            .HasColumnName("excerpt");

                        b1.HasKey("PostId");

                        b1.ToTable("posts");

                        b1.WithOwner()
                            .HasForeignKey("PostId");
                    });

                b.OwnsOne("LiteNova.Blog.Domain.Posts.PostSlug", "Slug", b1 =>
                    {
                        b1.Property<Guid>("PostId")
                            .HasColumnType("uuid");

                        b1.Property<string>("Value")
                            .IsRequired()
                            .HasMaxLength(300)
                            .HasColumnType("character varying(300)")
                            .HasColumnName("slug");

                        b1.HasKey("PostId");

                        b1.HasIndex("Value")
                            .IsUnique()
                            .HasDatabaseName("uq_posts_slug");

                        b1.ToTable("posts");

                        b1.WithOwner()
                            .HasForeignKey("PostId");
                    });

                b.OwnsOne("LiteNova.Blog.Domain.Posts.PostTitle", "Title", b1 =>
                    {
                        b1.Property<Guid>("PostId")
                            .HasColumnType("uuid");

                        b1.Property<string>("Value")
                            .IsRequired()
                            .HasMaxLength(200)
                            .HasColumnType("character varying(200)")
                            .HasColumnName("title");

                        b1.HasKey("PostId");

                        b1.ToTable("posts");

                        b1.WithOwner()
                            .HasForeignKey("PostId");
                    });

                b.Navigation("Content")
                    .IsRequired();

                b.Navigation("CoverImageUrl");

                b.Navigation("Excerpt");

                b.Navigation("Slug")
                    .IsRequired();

                b.Navigation("Title")
                    .IsRequired();
            });

        modelBuilder.Entity("LiteNova.Blog.Domain.Posts.PostTag", b =>
            {
                b.HasOne("LiteNova.Blog.Domain.Posts.Post", null)
                    .WithMany("Tags")
                    .HasForeignKey("PostId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("LiteNova.Blog.Domain.Tags.Tag", b =>
            {
                b.OwnsOne("LiteNova.Blog.Domain.Tags.TagName", "Name", b1 =>
                    {
                        b1.Property<Guid>("TagId")
                            .HasColumnType("uuid");

                        b1.Property<string>("Value")
                            .IsRequired()
                            .HasMaxLength(50)
                            .HasColumnType("character varying(50)")
                            .HasColumnName("name");

                        b1.HasKey("TagId");

                        b1.HasIndex("Value")
                            .IsUnique()
                            .HasDatabaseName("uq_tags_name");

                        b1.ToTable("tags");

                        b1.WithOwner()
                            .HasForeignKey("TagId");
                    });

                b.OwnsOne("LiteNova.Blog.Domain.Tags.TagSlug", "Slug", b1 =>
                    {
                        b1.Property<Guid>("TagId")
                            .HasColumnType("uuid");

                        b1.Property<string>("Value")
                            .IsRequired()
                            .HasMaxLength(100)
                            .HasColumnType("character varying(100)")
                            .HasColumnName("slug");

                        b1.HasKey("TagId");

                        b1.HasIndex("Value")
                            .IsUnique()
                            .HasDatabaseName("uq_tags_slug");

                        b1.ToTable("tags");

                        b1.WithOwner()
                            .HasForeignKey("TagId");
                    });

                b.Navigation("Name")
                    .IsRequired();

                b.Navigation("Slug")
                    .IsRequired();
            });

        modelBuilder.Entity("LiteNova.Blog.Domain.Posts.Post", b =>
            {
                b.Navigation("Tags");
            });
#pragma warning restore 612, 618
    }
}
