global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Threading;
global using System.Threading.Tasks;
global using LiteNova.Blog.Domain.Authors;
global using LiteNova.Blog.Domain.Posts;
global using LiteNova.Blog.Domain.Tags;
global using Microsoft.EntityFrameworkCore;
