<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\LiteNova.LitePress.Application.Write.Contracts\LiteNova.LitePress.Application.Write.Contracts.csproj" />
    <ProjectReference Include="..\LiteNova.LitePress.Domain\LiteNova.LitePress.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="LiteBus.Commands.Abstractions" />
  </ItemGroup>
</Project>
