<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\LiteNova.Blog.Application.Read.Contracts\LiteNova.Blog.Application.Read.Contracts.csproj" />
    <ProjectReference Include="..\LiteNova.Blog.Domain\LiteNova.Blog.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="LiteBus.Queries.Abstractions" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
  </ItemGroup>
</Project>
