<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\LiteNova.LitePress.Domain\LiteNova.LitePress.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="LiteBus.Queries.Abstractions" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
  </ItemGroup>
</Project>
