<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\LiteNova.Blog.Application.Write.Contracts\LiteNova.Blog.Application.Write.Contracts.csproj" />
    <ProjectReference Include="..\LiteNova.Blog.Domain\LiteNova.Blog.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="LiteBus.Commands.Abstractions" />
  </ItemGroup>
</Project>
